const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function hash(s){let h=2166136261;for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function meters(a,b,w){return Math.hypot((a.x-b.x)*(w.grid.w-1)*w.grid.cellMeters,(a.y-b.y)*(w.grid.h-1)*w.grid.cellMeters)}
function light(w){const solar=clamp(w.weather?.solar??0),cloud=clamp(w.weather?.cloud??.5);return{solar,cloud,shadowStrength:+clamp(solar*(1-cloud*.55)).toFixed(3),colorTemperature_K:solar>.45?5400:solar>.12?6100:7200}}
function identity(a){const h=hash(a.id);return{seed:h,continuityKey:`human:${a.id}`,synthetic:true,regionPrior:'Penonome, Cocle, Panama',age:['young-adult','adult','adult','middle-age'][h%4],presentation:['masculine','feminine','neutral'][(h>>>4)%3],skin:['medium-deep','medium','medium-warm','tan','light-medium'][(h>>>7)%5],hair:['dark-straight','dark-wavy','dark-curly','short-dark'][(h>>>11)%4],clothes:['everyday-lightweight','casual-urban','workwear-light','everyday-neutral'][(h>>>15)%4],rule:'generate a unique synthetic person; never reproduce a real identity'}}
function dynamics(a){const dx=Number.isFinite(a.tx)?a.tx-a.x:0,dy=Number.isFinite(a.ty)?a.ty-a.y:0,moving=Math.hypot(dx,dy)>.003;return{pose:moving?'walk':'idle',velocityDirection:moving?{x:dx,y:dy}:null,target:Number.isFinite(a.tx)&&Number.isFinite(a.ty)?{x:a.tx,y:a.ty}:null,need:a.need||null,energy:a.energy??null,hydration:a.hydration??null}}
function graph(agents,w){const edges=[];for(const a of agents){let b=null,d=Infinity;for(const q of agents)if(q!==a){const x=meters(a,q,w);if(x<d){d=x;b=q}}if(b&&d<8)edges.push({a:a.id,b:b.id,distanceM:+d.toFixed(2),kind:d<2.6?'social-range':'awareness',constraint:d<2.6?'mutual orientation allowed; conversation only if causal state asserts it':'visual awareness only'})}return edges}
export function buildAppearanceScenePacket(w,camera={}){const ir=w.representation||{},agents=ir.entities?.agents||w.agents||[],plants=ir.entities?.plants||w.plants||[],animals=ir.entities?.animals||w.animals||[],edges=graph(agents,w);return{schema:3,type:'atlas-neural-render-state',authority:'observer-only',frame:{cycle:w.cycle,time:w.updatedAt,region:'Penonome',anchor:w.geo?.anchor||ir.frame?.anchor||null,camera:{fov_deg:camera.fov??58,height_m:camera.height_m??1.65,yaw_deg:camera.yaw_deg??null,pitch_deg:camera.pitch_deg??null,position:camera.position??null}},world:{weather:w.weather,light:light(w),terrain:{cellMeters:w.grid?.cellMeters,cells:w.grid?.cells?.map((c,i)=>({i,elevation:c.elevation,soil:c.soil,landCover:c.landCover}))||[]},roads:ir.context?.roads||w.geodata?.roads||null,hydrography:ir.context?.hydrography||w.geodata?.hydrography||null},entities:{humans:agents.map(a=>({id:a.id,position:{x:a.x,y:a.y,geo:a.geo||null},identity:identity(a),dynamics:dynamics(a)})),plants:plants.map(p=>({id:p.id,position:{x:p.x,y:p.y,geo:p.geo||null},species:p.kind||p.species,biomassKg:p.biomassKg??p.biomass,health:p.health,stage:p.stage})),animals:animals.map(a=>({id:a.id,species:a.species||a.kind,position:{x:a.x,y:a.y,geo:a.geo||null},state:a.state||null})),atlas:ir.entities?.atlas||w.atlas||null},interactionGraph:edges,renderContract:{mode:'state-conditioned-neural-render',target:'temporally coherent photographic realism',geometryPolicy:'minimal spatial constraints; do not require display meshes',continuity:['same entity id => same synthetic identity','preserve positions, occlusion ordering and motion across frames','derive sun, shadows, wetness and vegetation appearance from state','no visible entity without causal-state provenance'],inferenceAllowed:['photographic material microtexture','synthetic facial detail','clothing detail consistent with prior','subvisual geometry needed to rasterize appearance'],forbidden:['copy real faces','invent people, animals, buildings or events','move causal entities for composition','convert proximity into a factual conversation','overwrite world state from rendered pixels'],feedback:'renderer is an observer: pixels never become causal truth unless separately observed and verified'}}}}
if(typeof window!=='undefined')window.AtlasAppearance={buildAppearanceScenePacket};
