'use strict';

const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function hash(s){let h=2166136261;for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function geoDistanceM(a,b,w){const dx=(a.x-b.x)*(w.grid.w-1)*w.grid.cellMeters,dy=(a.y-b.y)*(w.grid.h-1)*w.grid.cellMeters;return Math.hypot(dx,dy)}
function landSummary(w){const m=new Map;for(const c of w.grid?.cells||[]){const k=c.landCover?.className||'unknown';m.set(k,(m.get(k)||0)+1)}return [...m].sort((a,b)=>b[1]-a[1]).map(([className,cells])=>({className,cells,fraction:+(cells/(w.grid?.cells?.length||1)).toFixed(4)}))}
function light(w){const solar=clamp(w.weather?.solar??0),cloud=clamp(w.weather?.cloud??.5);return{solar,cloud,quality:solar>.58?'direct tropical daylight':solar>.18?'soft tropical daylight':'low ambient light',shadowStrength:+clamp(solar*(1-cloud*.55)).toFixed(3),colorTemperaturePrior_K:solar>.45?5400:solar>.12?6100:7200,truth:'derived visual parameter; not causal state'}}
function humanAppearance(a){const h=hash(a.id);return{identitySeed:h,identity:'synthetic-stable',regionalPrior:'Panama/Cocle',ageBandPrior:['young-adult','adult','adult','middle-age'][h%4],presentationPrior:['masculine','feminine','neutral'][(h>>>4)%3],skinTonePrior:['medium-deep','medium','medium-warm','tan','light-medium'][(h>>>7)%5],hairPrior:['dark-straight','dark-wavy','dark-curly','short-dark'][(h>>>11)%4],clothingPrior:['everyday-lightweight','casual-urban','workwear-light','everyday-neutral'][(h>>>15)%4],traditionalAccessoryPrior:(h>>>19)%17===0?'possible-regional-hat':'none',policy:'appearance prior only; never claim demographic truth or copy a real person'}}
function action(a){if(a.need==='water')return'seeking water';if(a.need==='rest')return'resting/recovering';if(a.need==='explore')return'exploring local environment';return a.need||'present in environment'}
function relationships(agents,w){const out=[];for(let i=0;i<agents.length;i++){let best=null,d=Infinity;for(let j=0;j<agents.length;j++)if(i!==j){const q=geoDistanceM(agents[i],agents[j],w);if(q<d){d=q;best=agents[j]}}if(best&&d<8)out.push({from:agents[i].id,to:best.id,relation:d<2?'close-presence':'nearby',distanceM:+d.toFixed(2),visualPermission:'may imply awareness/body orientation only; not conversation unless causal state says so'})}return out}
export function buildAppearanceScenePacket(w,camera={}){const ir=w.representation||{},agents=ir.entities?.agents||w.agents||[],plants=ir.entities?.plants||w.plants||[],a=w.geo?.anchor||ir.frame?.anchor||null;return{schema:1,type:'atlas-photographic-scene-packet',authority:'observer-only',source:{world:'world-state.json',cycle:w.cycle,updatedAt:w.updatedAt,representation:ir.type||'spatial-intermediate-representation'},region:{name:'Penonome',province:w.geo?.admin?.province||'Cocle',country:'Panama',anchor:a,truth:'from world geodata'},camera:{fov_deg:camera.fov??58,height_m:camera.height_m??1.65,yaw_deg:camera.yaw_deg??null,pitch_deg:camera.pitch_deg??null,position:camera.position??null},environment:{weather:{tempC:w.weather?.tempC,humidity:w.weather?.humidity,wind:w.weather?.wind,rainMm:w.weather?.rainMm},lighting:light(w),terrain:{cellMeters:w.grid?.cellMeters,truthStatus:w.grid?.provenance?.terrainTruth||w.grid?.provenance?.terrainStatus,elevationUnits:w.grid?.provenance?.terrainUnits||'unknown'},landCover:landSummary(w),hydrography:ir.context?.hydrography||w.geodata?.hydrography||null,roads:ir.context?.roads||w.geodata?.roads||null},entities:{humans:agents.map(x=>({id:x.id,x:x.x,y:x.y,geo:x.geo||null,action:action(x),appearance:humanAppearance(x)})),plants:plants.map(x=>({id:x.id,kind:x.kind||x.species,x:x.x,y:x.y,geo:x.geo||null,biomassKg:x.biomassKg,health:x.health,stage:x.stage,appearanceRule:'derive visible size/species-form from causal biomass/health only'})),atlas:ir.entities?.atlas||w.atlas||null,animals:(ir.entities?.animals||w.animals||[]).map(x=>({...x,appearanceRule:'photographic species appearance; no animal may be added if absent from causal state'}))},relationships:relationships(agents,w),decoder:{qualityTarget:'photographic-realistic',temporalIdentity:'stable by entity id',culturalContext:'Panamanian/Cocle prior without caricature',hardRules:['do not create/delete/relocate causal entities','do not copy real faces','do not invent interactions as causal facts','photographic texture/material/light may be inferred','unknown remains unknown when it affects world truth']}}}

if(typeof window!=='undefined')window.AtlasAppearance={buildAppearanceScenePacket};
