import * as T from 'https://cdn.jsdelivr.net/npm/three@0.168.0/build/three.module.js';

const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const skin=[0x7a4b2d,0x915d3b,0xa76d47,0xbc8058,0xcf946b,0xdba77f];
const shirts=[0xe8e0d2,0xd5cab5,0x7593a8,0x697c58,0xb8a37d,0x8d6e63,0xf0eadc,0x9d6a54];
const pants=[0x29323a,0x3a403f,0x554b3e,0x24354a,0x5b5a50];
const hair=[0x17130f,0x251c17,0x31251d,0x111111];
function hash(s){let h=2166136261;for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function pick(a,h,n=0){return a[((h+n*2654435761)>>>0)%a.length]}
function mat(c,r=.82){return new T.MeshStandardMaterial({color:c,roughness:r})}
function dispose(o){o.traverse?.(n=>{n.geometry?.dispose?.();if(Array.isArray(n.material))n.material.forEach(m=>m.dispose?.());else n.material?.dispose?.()})}
function distM(a,b,w){return Math.hypot((a.x-b.x)*(w.grid.w-1)*w.grid.cellMeters,(a.y-b.y)*(w.grid.h-1)*w.grid.cellMeters)}

export class AtlasDynamicsObserver{
  constructor(root=document.body){
    this.scene=new T.Scene();
    this.camera=new T.PerspectiveCamera(58,innerWidth/innerHeight,.1,260);
    this.renderer=new T.WebGLRenderer({antialias:true});
    this.renderer.setSize(innerWidth,innerHeight);this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));
    this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.08;this.renderer.shadowMap.enabled=true;
    root.append(this.renderer.domElement);
    this.world=new T.Group();this.scene.add(this.world);
    this.hemi=new T.HemisphereLight(0xdcecff,0x443826,1.6);this.sun=new T.DirectionalLight(0xffd8a3,3.3);this.sun.position.set(-18,25,15);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);this.scene.add(this.hemi,this.sun);
    this.state=null;this.characters=new Map();this.plants=[];this.static=[];this.cellScale=.315;this.baseElevation=0;this.heightScale=.12;this.transitionMs=4200;this.wind=.2;
    this.target=new T.Vector3(0,1,0);this.yaw=.72;this.pitch=-.16;this.distance=8.5;this.drag=false;this.lx=0;this.ly=0;
    this.bindControls();this.updateCamera();this.loop= this.loop.bind(this);requestAnimationFrame(this.loop);
    addEventListener('resize',()=>{this.renderer.setSize(innerWidth,innerHeight);this.updateCamera()});
  }
  bindControls(){const c=this.renderer.domElement;c.style.touchAction='none';c.onpointerdown=e=>{this.drag=true;this.lx=e.clientX;this.ly=e.clientY};onpointerup=()=>this.drag=false;onpointermove=e=>{if(!this.drag)return;this.yaw-=(e.clientX-this.lx)*.006;this.pitch=Math.max(-.5,Math.min(-.04,this.pitch-(e.clientY-this.ly)*.004));this.lx=e.clientX;this.ly=e.clientY;this.updateCamera()}}
  updateCamera(){const p=Math.cos(this.pitch);this.camera.position.set(this.target.x+Math.sin(this.yaw)*p*this.distance,this.target.y+Math.sin(-this.pitch)*this.distance,this.target.z+Math.cos(this.yaw)*p*this.distance);this.camera.lookAt(this.target);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix()}
  cell(w,x,y){x=clamp(x,0,w.grid.w-1);y=clamp(y,0,w.grid.h-1);return w.grid.cells[y*w.grid.w+x]}
  elevationAt(w,x,y){const c=this.cell(w,Math.floor(x*w.grid.w),Math.floor(y*w.grid.h));return((+c?.elevation||0)-this.baseElevation)*this.heightScale}
  pos(w,x,y){return[(x-.5)*(w.grid.w-1)*this.cellScale,(y-.5)*(w.grid.h-1)*this.cellScale]}
  clearStatic(){for(const o of this.static){this.world.remove(o);dispose(o)}this.static=[];for(const p of this.plants){this.world.remove(p);dispose(p)}this.plants=[]}
  buildGround(w){let v=[],co=[],ix=[];for(let y=0;y<w.grid.h;y++)for(let x=0;x<w.grid.w;x++){const q=this.cell(w,x,y),m=q.soil?.moisture||0,o=q.soil?.organic||0,k=new T.Color().setHSL(.09+o*.025,.3+o*.12,.3+m*.1);v.push((x-(w.grid.w-1)/2)*this.cellScale,((+q.elevation||0)-this.baseElevation)*this.heightScale,(y-(w.grid.h-1)/2)*this.cellScale);co.push(k.r,k.g,k.b)}for(let y=0;y<w.grid.h-1;y++)for(let x=0;x<w.grid.w-1;x++){const a=y*w.grid.w+x,b=a+1,d=a+w.grid.w,e=d+1;ix.push(a,d,b,b,d,e)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setAttribute('color',new T.Float32BufferAttribute(co,3));g.setIndex(ix);g.computeVertexNormals();const m=new T.Mesh(g,new T.MeshStandardMaterial({vertexColors:true,roughness:.96}));m.receiveShadow=true;this.world.add(m);this.static.push(m)}
  makePlant(p){const g=new T.Group(),kind=p.kind||p.species,bio=Math.max(.02,p.biomassKg??p.biomass??.02),h=hash(p.id);if(kind==='grass'){const n=Math.max(3,Math.min(9,3+Math.floor(bio*10)));for(let i=0;i<n;i++){const ht=.12+Math.min(.48,bio*.7)+(i%3)*.025,b=new T.Mesh(new T.ConeGeometry(.012,ht,3),mat(pick([0x315d2b,0x3c7034,0x477c3c],h,i),.95));b.position.set(((i%4)-1.5)*.018,ht/2,((i*7)%5-2)*.018);g.add(b)}}else{const s=.34+Math.min(1.2,Math.sqrt(bio)*.35),tr=new T.Mesh(new T.CylinderGeometry(.035*s,.065*s,.58*s,7),mat(0x5e412b,1));tr.position.y=.29*s;g.add(tr);for(let i=0;i<5;i++){const r=.19*s+(i%2)*.04*s,l=new T.Mesh(new T.IcosahedronGeometry(r,1),mat(pick([0x28532e,0x32653a,0x3d7141],h,i),.9));l.position.set(((i%3)-1)*.12*s,.58*s+(i%2)*.1*s,((i*2)%3-1)*.1*s);g.add(l)}}g.userData.phase=(h%628)/100;g.userData.plant=true;return g}
  limb(color,len=.28,rad=.045){const pivot=new T.Group(),mesh=new T.Mesh(new T.CapsuleGeometry(rad,len,3,6),mat(color,.82));mesh.position.y=-len*.48;pivot.add(mesh);return pivot}
  makeCharacter(a,isAtlas=false){const h=hash(a.id||a.name),g=new T.Group(),sc=isAtlas?1.04:.84,sk=isAtlas?0xc98a2f:pick(skin,h),shirt=isAtlas?0xb97a22:pick(shirts,h,2),pant=isAtlas?0x44301f:pick(pants,h,4);const hips=new T.Group();hips.position.y=.42*sc;g.add(hips);const torso=new T.Mesh(new T.CapsuleGeometry(.13*sc,.34*sc,4,8),mat(shirt,.76));torso.scale.set(1,.95,.68);torso.position.y=.31*sc;hips.add(torso);const headPivot=new T.Group();headPivot.position.y=.92*sc;hips.add(headPivot);const head=new T.Mesh(new T.SphereGeometry(.135*sc,16,10),mat(sk,.78));head.scale.set(.88,1.05,.9);headPivot.add(head);if(!isAtlas){const hm=new T.Mesh(new T.SphereGeometry(.138*sc,16,8,0,Math.PI*2,0,Math.PI*.48),mat(pick(hair,h,7),.95));hm.position.y=.03*sc;headPivot.add(hm);if((h>>>8)%13===0){const brim=new T.Mesh(new T.CylinderGeometry(.205*sc,.205*sc,.022*sc,22),mat(0xe4d3ad,.92)),crown=new T.Mesh(new T.CylinderGeometry(.11*sc,.13*sc,.12*sc,18),mat(0xe1cfaa,.92));brim.position.y=.16*sc;crown.position.y=.22*sc;headPivot.add(brim,crown)}}const leftArm=this.limb(sk,.27*sc,.042*sc),rightArm=this.limb(sk,.27*sc,.042*sc);leftArm.position.set(-.18*sc,.55*sc,0);rightArm.position.set(.18*sc,.55*sc,0);hips.add(leftArm,rightArm);const leftLeg=this.limb(pant,.3*sc,.052*sc),rightLeg=this.limb(pant,.3*sc,.052*sc);leftLeg.position.set(-.07*sc,.22*sc,0);rightLeg.position.set(.07*sc,.22*sc,0);g.add(leftLeg,rightLeg);g.userData={id:String(a.id||a.name),hips,headPivot,leftArm,rightArm,leftLeg,rightLeg,torso,phase:(h%1000)/100,from:null,to:null,t0:performance.now(),intent:null,social:null,isAtlas,scale:sc};g.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true}});return g}
  nearestRelations(w,entities){const rel=new Map();for(const a of entities){let best=null,d=Infinity;for(const b of entities)if(a!==b){const q=distM(a,b,w);if(q<d){d=q;best=b}}if(best)rel.set(String(a.id||a.name),{other:String(best.id||best.name),distance:d})}return rel}
  syncCharacters(w){const now=performance.now(),all=[...(w.agents||[]),...(w.atlas?[{...w.atlas,id:w.atlas.id||'atlas',_atlas:true}]:[])],relations=this.nearestRelations(w,all),seen=new Set;for(const a of all){const id=String(a.id||a.name),isAtlas=!!a._atlas;let g=this.characters.get(id);if(!g){g=this.makeCharacter(a,isAtlas);this.characters.set(id,g);this.world.add(g);const[x,z]=this.pos(w,a.x,a.y);g.position.set(x,this.elevationAt(w,a.x,a.y),z);g.userData.from={x:g.position.x,y:g.position.y,z:g.position.z}}else g.userData.from={x:g.position.x,y:g.position.y,z:g.position.z};const[x,z]=this.pos(w,a.x,a.y);g.userData.to={x,y:this.elevationAt(w,a.x,a.y),z};g.userData.t0=now;g.userData.intent={tx:a.tx,ty:a.ty,need:a.need||a.intent||'idle',energy:a.energy,hydration:a.hydration};g.userData.social=relations.get(id)||null;seen.add(id)}for(const[id,g]of this.characters)if(!seen.has(id)){this.world.remove(g);dispose(g);this.characters.delete(id)}}
  applyState(w){this.state=w;this.cellScale=(w.grid.cellMeters||4.5)*.07;this.baseElevation=Math.min(...w.grid.cells.map(q=>+q.elevation||0));this.wind=w.weather?.wind??.2;this.scene.background=new T.Color().setHSL(.55,.27,.43-(w.weather?.cloud??.5)*.12);this.scene.fog=new T.FogExp2(this.scene.background,.024);this.hemi.intensity=1.05+(w.weather?.solar??0)*1.7;this.sun.intensity=.6+(w.weather?.solar??0)*4;this.clearStatic();this.buildGround(w);for(const p of w.plants||[]){const q=this.makePlant(p),[x,z]=this.pos(w,p.x,p.y);q.position.set(x,this.elevationAt(w,p.x,p.y),z);this.world.add(q);this.plants.push(q)}this.syncCharacters(w)}
  animateCharacter(g,t){const u=Math.min(1,(t-(g.userData.t0||t))/this.transitionMs),s=u*u*(3-2*u),f=g.userData.from,to=g.userData.to;if(f&&to)g.position.set(f.x+(to.x-f.x)*s,f.y+(to.y-f.y)*s,f.z+(to.z-f.z)*s);const I=g.userData.intent||{},moving=f&&to&&Math.hypot(to.x-f.x,to.z-f.z)>.015,phase=t*.008+g.userData.phase;let targetAngle=null;if(this.state&&Number.isFinite(I.tx)&&Number.isFinite(I.ty)){const[x,z]=this.pos(this.state,I.tx,I.ty),dx=x-g.position.x,dz=z-g.position.z;if(Math.hypot(dx,dz)>.02)targetAngle=Math.atan2(dx,dz)}const social=g.userData.social;if(social&&social.distance<2.6){const other=this.characters.get(social.other);if(other){targetAngle=Math.atan2(other.position.x-g.position.x,other.position.z-g.position.z);g.userData.headPivot.rotation.y=Math.sin(t*.0015+g.userData.phase)*.18;g.userData.rightArm.rotation.x=-.55+Math.sin(t*.003+g.userData.phase)*.22;g.userData.leftArm.rotation.x=-.18;g.userData.hips.rotation.z=Math.sin(t*.002+g.userData.phase)*.025}}else if(moving&&I.need!=='rest'){const sw=Math.sin(phase)*.62;g.userData.leftArm.rotation.x=sw;g.userData.rightArm.rotation.x=-sw;g.userData.leftLeg.rotation.x=-sw*.75;g.userData.rightLeg.rotation.x=sw*.75;g.userData.hips.position.y=.42*g.userData.scale+Math.abs(Math.sin(phase))*0.025;g.userData.headPivot.rotation.y=0}else{const breath=Math.sin(t*.0018+g.userData.phase)*.012;g.userData.leftArm.rotation.x=.04;g.userData.rightArm.rotation.x=-.04;g.userData.leftLeg.rotation.x=0;g.userData.rightLeg.rotation.x=0;g.userData.hips.position.y=.42*g.userData.scale+breath;g.userData.headPivot.rotation.y=Math.sin(t*.0007+g.userData.phase)*.08}if(targetAngle!==null)g.rotation.y=targetAngle}
  loop(t){requestAnimationFrame(this.loop);for(const g of this.characters.values())this.animateCharacter(g,t);for(const p of this.plants)p.rotation.z=Math.sin(t*.0015+p.userData.phase)*Math.min(.13,.025+this.wind*.11);this.renderer.render(this.scene,this.camera)}
}
