'use strict';
const zlib=require('zlib');
const BASE='https://geoportal.miambiente.gob.pa/server/rest/services';
const SOURCES={
  municipal:{authority:'MiAmbiente / SINIA',url:`${BASE}/Nodo_Caracteristica_General/MapServer/1`,role:'official municipal-head fallback'},
  land:{authority:'MiAmbiente / SINIA',url:`${BASE}/Nodo_Suelos/MapServer`,layer:1,role:'2021 land-cover raster'},
  hydro:{authority:'MiAmbiente / SINIA',url:`${BASE}/Nodo_Caracteristica_General/MapServer`,layers:[10,11,12],role:'hydrography'},
  roads:{authority:'MiAmbiente / SINIA',url:`${BASE}/Nodo_Caracteristica_General/MapServer`,layers:[4,5,7],role:'roads'},
  terrain:{authority:'Mapzen / Linux Foundation via AWS Open Data',url:'https://s3.amazonaws.com/elevation-tiles-prod/skadi',role:'global bare-earth terrain heights; SRTM and other open DEM sources'}
};
const clean=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
async function json(url,ms=7000){const a=new AbortController(),t=setTimeout(()=>a.abort(),ms);try{const r=await fetch(url,{signal:a.signal,headers:{'user-agent':'Atlas-Reality-Stack/1.0'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
async function bytes(url,ms=20000){const a=new AbortController(),t=setTimeout(()=>a.abort(),ms);try{const r=await fetch(url,{signal:a.signal,headers:{'user-agent':'Atlas-Reality-Stack/1.0'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return Buffer.from(await r.arrayBuffer())}finally{clearTimeout(t)}}
function extent(anchor,grid){const h=grid.h*grid.cellMeters,w=grid.w*grid.cellMeters,latM=111320,lonM=latM*Math.cos(anchor.lat*Math.PI/180);return{minLat:anchor.lat-h/2/latM,maxLat:anchor.lat+h/2/latM,minLon:anchor.lon-w/2/lonM,maxLon:anchor.lon+w/2/lonM,width:w,height:h}}
function cellGeo(anchor,grid,c){const e=extent(anchor,grid);return{lat:e.maxLat-(c.y+.5)/grid.h*(e.maxLat-e.minLat),lon:e.minLon+(c.x+.5)/grid.w*(e.maxLon-e.minLon)}}
async function resolveAnchor(s){if(s.geo?.anchor?.source==='miambienteMunicipalHead')return s.geo.anchor;const q=new URLSearchParams({where:'1=1',outFields:'CABEC_MUNI,MUNI,DEPTO',returnGeometry:'true',outSR:'4326',f:'json'});try{const j=await json(`${SOURCES.municipal.url}/query?${q}`),f=(j.features||[]).find(v=>clean(v.attributes?.CABEC_MUNI).includes('penonome')||clean(v.attributes?.MUNI).includes('penonome'));if(!f?.geometry)throw Error('Penonomé not returned');s.geo=s.geo||{};s.geo.anchor={lat:+f.geometry.y.toFixed(7),lon:+f.geometry.x.toFixed(7),crs:'EPSG:4326',source:'miambienteMunicipalHead',verifiedAt:new Date().toISOString()};s.geo.admin={...(s.geo.admin||{}),district:f.attributes?.MUNI||'Penonomé',province:f.attributes?.DEPTO||'Coclé'};return s.geo.anchor}catch(e){s.geodata=s.geodata||{};s.geodata.anchorError=String(e.message||e);return s.geo?.anchor}}
function skadiName(lat,lon){const la=Math.floor(lat),lo=Math.floor(lon),ns=`${la>=0?'N':'S'}${String(Math.abs(la)).padStart(2,'0')}`,ew=`${lo>=0?'E':'W'}${String(Math.abs(lo)).padStart(3,'0')}`;return{dir:ns,file:`${ns}${ew}.hgt.gz`,lat0:la,lon0:lo}}
function hgtValue(buf,n,row,col){row=Math.max(0,Math.min(n-1,row));col=Math.max(0,Math.min(n-1,col));return buf.readInt16BE((row*n+col)*2)}
function sampleHgt(buf,n,lat,lon,lat0,lon0){const y=(lat0+1-lat)*(n-1),x=(lon-lon0)*(n-1),x0=Math.floor(x),y0=Math.floor(y),x1=Math.min(n-1,x0+1),y1=Math.min(n-1,y0+1),tx=x-x0,ty=y-y0,v=[hgtValue(buf,n,y0,x0),hgtValue(buf,n,y0,x1),hgtValue(buf,n,y1,x0),hgtValue(buf,n,y1,x1)];if(v.some(q=>q<=-32768))return null;return v[0]*(1-tx)*(1-ty)+v[1]*tx*(1-ty)+v[2]*(1-tx)*ty+v[3]*tx*ty}
async function terrain(s){if(s.grid?.provenance?.terrainTruth==='open-dem-calibrated')return;const a=s.geo?.anchor;if(!a)throw Error('anchor unavailable');const t=skadiName(a.lat,a.lon),raw=zlib.gunzipSync(await bytes(`${SOURCES.terrain.url}/${t.dir}/${t.file}`)),n=Math.sqrt(raw.length/2);if(!Number.isInteger(n))throw Error(`unexpected HGT size ${raw.length}`);let ok=0;for(const c of s.grid.cells){const g=cellGeo(a,s.grid,c),z=sampleHgt(raw,n,g.lat,g.lon,t.lat0,t.lon0);if(z==null)continue;c.legacyElevation=c.legacyElevation??c.elevation;c.elevation=+z.toFixed(3);c.elevationM=c.elevation;c.provenance=c.provenance||{};c.provenance.terrain='aws-terrain-tiles-skadi';ok++}if(ok<s.grid.cells.length*.9)throw Error(`only ${ok}/${s.grid.cells.length} DEM samples`);s.grid.provenance={...(s.grid.provenance||{}),terrainTruth:'open-dem-calibrated',terrainUnits:'m',terrainSource:'awsTerrainTiles',terrainSourceResolution:`HGT ${n}x${n} per degree`,calibratedAt:new Date().toISOString()}}
function bmp(buf){if(buf.toString('ascii',0,2)!=='BM')throw Error('export was not BMP');const off=buf.readUInt32LE(10),w=buf.readInt32LE(18),h0=buf.readInt32LE(22),bpp=buf.readUInt16LE(28),h=Math.abs(h0);if(![24,32].includes(bpp))throw Error(`BMP bpp ${bpp}`);const stride=Math.ceil(w*bpp/32)*4;return{w,h,get(x,y){const yy=h0>0?h-1-y:y,i=off+yy*stride+x*bpp/8;return[buf[i+2],buf[i+1],buf[i]]}}}
async function land(s){if(s.geodata?.landCover?.calibratedAt)return;const a=s.geo?.anchor;if(!a)throw Error('anchor unavailable');const pq=new URLSearchParams({where:'1=1',outFields:'Classvalue,Class_name,Red,Green,Blue',returnGeometry:'false',f:'json'}),pj=await json(`${SOURCES.land.url}/${SOURCES.land.layer}/query?${pq}`),palette=(pj.features||[]).map(f=>f.attributes).filter(x=>Number.isFinite(+x.Red)&&Number.isFinite(+x.Green)&&Number.isFinite(+x.Blue));if(!palette.length)throw Error('land-cover palette unavailable');const e=extent(a,s.grid),ep=new URLSearchParams({bbox:`${e.minLon},${e.minLat},${e.maxLon},${e.maxLat}`,bboxSR:'4326',imageSR:'4326',size:`${s.grid.w},${s.grid.h}`,format:'bmp',transparent:'false',layers:`show:${SOURCES.land.layer}`,f:'image'}),im=bmp(await bytes(`${SOURCES.land.url}/export?${ep}`));if(im.w!==s.grid.w||im.h!==s.grid.h)throw Error(`land raster ${im.w}x${im.h}`);let maxD=0;for(const c of s.grid.cells){const rgb=im.get(c.x,c.y);let best=null,bd=Infinity;for(const p of palette){const d=Math.hypot(rgb[0]-p.Red,rgb[1]-p.Green,rgb[2]-p.Blue);if(d<bd){bd=d;best=p}}maxD=Math.max(maxD,bd);c.landCover={classValue:+best.Classvalue,className:best.Class_name,rgb:[+best.Red,+best.Green,+best.Blue],renderColorDistance:+bd.toFixed(2),source:'miambienteLand2021'}}s.geodata=s.geodata||{};s.geodata.landCover={calibratedAt:new Date().toISOString(),source:'miambienteLand2021',paletteClasses:palette.length,maxRenderColorDistance:+maxD.toFixed(2),method:'single official raster export decoded by RGB class palette'}}
async function vectorLayer(root,id,e){const q=new URLSearchParams({where:'1=1',geometry:`${e.minLon},${e.minLat},${e.maxLon},${e.maxLat}`,geometryType:'esriGeometryEnvelope',inSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'*',returnGeometry:'true',outSR:'4326',f:'json'});const j=await json(`${root}/${id}/query?${q}`);return(j.features||[]).map(f=>({layer:id,attributes:f.attributes||{},geometry:f.geometry||null}))}
async function vectors(s){const a=s.geo?.anchor;if(!a)throw Error('anchor unavailable');const e=extent(a,s.grid),[h,r]=await Promise.all([Promise.all(SOURCES.hydro.layers.map(id=>vectorLayer(SOURCES.hydro.url,id,e))),Promise.all(SOURCES.roads.layers.map(id=>vectorLayer(SOURCES.roads.url,id,e)))]);s.geodata=s.geodata||{};s.geodata.hydrography={source:'miambienteHydro',queriedAt:new Date().toISOString(),features:h.flat()};s.geodata.roads={source:'miambienteRoads',queriedAt:new Date().toISOString(),features:r.flat()}}
function normalGravity(lat){const p=lat*Math.PI/180,s=Math.sin(p),s2=s*s;return 9.7803253359*(1+.00193185265241*s2)/Math.sqrt(1-.00669437999013*s2)}
async function enrich(s){s.geodata=s.geodata||{};s.geodata.sources=SOURCES;const a=await resolveAnchor(s);if(a){s.physicsConstants=s.physicsConstants||{system:'SI',values:{}};s.physicsConstants.values=s.physicsConstants.values||{};s.physicsConstants.values.WGS84NormalGravityAtAnchor_m_s2=+normalGravity(a.lat).toFixed(9)}const jobs=[['terrain',terrain],['land',land],['vectors',vectors]];const out=await Promise.allSettled(jobs.map(([,fn])=>fn(s)));s.geodata.checks=s.geodata.checks||{};out.forEach((x,i)=>s.geodata.checks[jobs[i][0]]=x.status==='fulfilled'?{ok:true,at:new Date().toISOString()}:{ok:false,at:new Date().toISOString(),error:String(x.reason?.message||x.reason)});return s}
module.exports={enrich,SOURCES,normalGravity,extent,cellGeo};
