import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.168.0/build/three.module.js';
import {loadPanama,project} from './panama-geometry.js';
const scene=new THREE.Scene();scene.background=new THREE.Color(0xa9c5c7);scene.fog=new THREE.FogExp2(0xa9c5c7,.0028);
const camera=new THREE.PerspectiveCamera(50,innerWidth/innerHeight,.1,2000);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;document.body.prepend(renderer.domElement);Object.assign(renderer.domElement.style,{position:'fixed',inset:'0',zIndex:'2',touchAction:'none'});['scene','fx','liveWorld'].forEach(id=>{const e=document.getElementById(id);if(e)e.style.display='none'});
scene.add(new THREE.HemisphereLight(0xfff2d6,0x24422f,2.4));const sun=new THREE.DirectionalLight(0xffcb82,4);sun.position.set(-120,180,80);scene.add(sun);const ocean=new THREE.Mesh(new THREE.PlaneGeometry(800,500),new THREE.MeshStandardMaterial({color:0x2f7180,roughness:.3}));ocean.rotation.x=-Math.PI/2;ocean.position.y=-1.5;scene.add(ocean);const land=new THREE.Group(),city=new THREE.Group(),nature=new THREE.Group(),agents=new THREE.Group();scene.add(land,city,nature,agents);
function box(x,z,w,d,h,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:c,roughness:.8}));m.position.set(x,h/2+1.7,z);m.castShadow=true;m.receiveShadow=true;city.add(m)}function tree(x,z,s=.6){const t=new THREE.Mesh(new THREE.CylinderGeometry(.12*s,.16*s,.9*s,6),new THREE.MeshStandardMaterial({color:0x57422f}));t.position.set(x,2+(.45*s),z);const c=new THREE.Mesh(new THREE.IcosahedronGeometry(.72*s,1),new THREE.MeshStandardMaterial({color:0x28543a}));c.position.set(x,2.8*s+1.3,z);nature.add(t,c)}
const [PX,PZ0]=project([-80.35468,8.51208]),PZ=-PZ0;function buildPenonome(){for(let i=-4;i<=4;i++)for(let j=-4;j<=4;j++){const x=PX+i*4.8,z=PZ+j*4.1,s=Math.abs(i*31+j*17);if((i+j)%5===0){tree(x,z,.9);continue}if(Math.abs(i)<=1&&Math.abs(j)<=1)continue;box(x,z,2.2+(s%3)*.5,2.4+(s%2)*.5,2.8+(s%7)*.75,s%4===0?0xb99f75:0xd1c5a5)}for(let i=0;i<100;i++){const a=i*2.399,r=12+(i%16)*1.9;tree(PX+Math.cos(a)*r,PZ+Math.sin(a)*r,.5+(i%3)*.15)}}
async function world(){try{const w=await fetch('world-state.json?'+Date.now(),{cache:'no-store'}).then(r=>r.json());agents.clear();for(const a of w.agents||[]){const x=PX+(a.x-.5)*28,z=PZ+(a.y-.5)*24,m=new THREE.Mesh(new THREE.CapsuleGeometry(.18,.55,3,5),new THREE.MeshStandardMaterial({color:0xd7ddd4}));m.position.set(x,2.8,z);agents.add(m)}if(w.atlas){const x=PX+(w.atlas.x-.5)*28,z=PZ+(w.atlas.y-.5)*24,m=new THREE.Mesh(new THREE.CapsuleGeometry(.3,.9,4,8),new THREE.MeshStandardMaterial({color:0xefbd68,emissive:0x6c4a14}));m.position.set(x,3.1,z);agents.add(m);const h=new THREE.Mesh(new THREE.TorusGeometry(.7,.08,8,32),new THREE.MeshBasicMaterial({color:0xefbd68}));h.rotation.x=Math.PI/2;h.position.set(x,3.8,z);agents.add(h)}}catch(e){console.warn(e)}}
let yaw=0,pitch=-.45,dist=245,drag=false,lx=0,ly=0;const target=new THREE.Vector3(0,0,0);function cam(){const cp=Math.cos(pitch);camera.position.set(Math.sin(yaw)*cp*dist,Math.sin(-pitch)*dist,Math.cos(yaw)*cp*dist);camera.lookAt(target)}cam();renderer.domElement.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-lx)*.006;pitch=Math.max(-1.15,Math.min(-.08,pitch-(e.clientY-ly)*.004));lx=e.clientX;ly=e.clientY;cam()});let pinch=0;renderer.domElement.addEventListener('touchmove',e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch)dist=Math.max(40,Math.min(350,dist-(d-pinch)*.35));pinch=d;cam()}},{passive:true});renderer.domElement.addEventListener('touchend',()=>pinch=0,{passive:true});
loadPanama(land).then(buildPenonome).catch(console.error);world();setInterval(world,15000);function loop(t){requestAnimationFrame(loop);ocean.material.color.setHSL(.52,.42,.31+Math.sin(t*.00025)*.018);renderer.render(scene,camera)}loop(0);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
